project:
  type: book
  output-dir: docs
  preview:
    port: 4000
    browser: true

toc: true
toc-title: content

number-sections: true
number-depth: 2

bibliography: references.bib


book:
  title: "Python TAP (Theory, Application and Practice)"
  author: "Samyar Modabber"
  date: "30/03/2021"
  image: logo.png
  # cover-image: logo.png
  favicon: logo.png
  reader-mode: true
  
  search:
    location: navbar
    type: overlay

  navbar:
      pinned: true
      logo: logo.png
      right:
      # - title: "Math"
      - icon: github
        href: https://github.com/samyarmodabber/pythonTAP
        aria-label: GitHub
      
  sidebar:
    alignment: left
    search: true
    logo: logo.png
  # page-footer:
  #   center: 
  #     - text: "درباره ما"
  #       href: pages/about.qmd
      # - text: "License"
      #   href: pages/license.qmd
  chapters:
    - index.qmd
    - part: "Built-in Data Types"
      chapters:
        - chapters/01Build-inDataType/01_boolean.qmd
        - chapters/01Build-inDataType/02_numeric.qmd
        - chapters/01Build-inDataType/03_string.qmd
        - chapters/01Build-inDataType/04_list.qmd
        - chapters/01Build-inDataType/05_set.qmd
        - chapters/01Build-inDataType/06_dict.qmd
        - chapters/01Build-inDataType/07_binary.qmd
        # - chapters/01Build-inDataType/11_bytes.qmd
        # - chapters/01Build-inDataType/12_bytearray.qmd
        # - chapters/01Build-inDataType/13_memoryview.qmd
    - part: "Practice"
      chapters:
        - chapters/01/01-basic-and-string.ipynb
        - chapters/02/02-integers-and-float.ipynb
        - chapters/03/03-data-structures.ipynb
        - chapters/04/04-conditions-and-loops.ipynb
        - chapters/05/05-functions.ipynb
        # - chapters/06/06-modules.ipynb
        # - chapters/07/07-classes.ipynb
        # - chapters/08/08-exceptions.ipynb
        # - chapters/09/09-files.ipynb
    # - part: "Classes and Objects"
    #   chapters:
    #     - chapters/10/10-classes.ipynb

    - references.qmd

# https://github.com/mlr-org/mlr3book/blob/main/book/_quarto.yml
format:
  html:
    theme:
      dark: [darkly , style/custom.scss]
      light: [cosmo , style/custom.scss]
    fontsize: "17px"
    linestretch: 1.6
    mainfont: "Roboto"
    monofont: "Fira Mono"
    smooth-scroll: true
    toc-depth: 2
    # code-link: false
    # code-tools:
    #   toggle: true
    # code-fold: false
    highlight-style: printing
    # code-block-bg: true
    # code-overflow: wrap
    reference-location: margin
    mermaid:
      theme: neutral


